### ISSUE TITLE
How must proxy list look like?

### ISSUE THREAD

**Issue by Marow** [hartleybrody/public-amazon-crawler#10]
I buyed some proxys from proxybonanza.

But when i will start crawler.py 
`python crawler.py start`

Its showing 
`2018-03-20 19:50:44.586334: Seeding the URL frontier with subcategory URLs`

But nothing doing than... there nothing coming anymore...

**Comment by hartleybrody** [comment]
The list just needs to contain the IP addresses. I set things up so that the username and password are global across all of the proxy servers, which (I believe) is how proxybonanza does it.

[You can see where the proxy list is used, to give you a better sense.](https://github.com/hartleybrody/public-amazon-crawler/blob/b7b1570b117732a755a5fd5e95c91d0f41930887/helpers.py#L82)

**Comment by Marow** [comment]
Its working now. Using SOCK5 Port :) 

One Question. If i run it again, he crawls and save the URLs again that he already saved or he overwrite the price of them?
