### ISSUE TITLE
postgreSQL

### ISSUE THREAD

**Issue by yevheniy2407** [hartleybrody/public-amazon-crawler#16]
```
root@4-8-CPU-Optimized:/crawler# python models.py
Traceback (most recent call last):
  File "models.py", line 5, in <module>
    conn = psycopg2.connect(database=settings.database, host=settings.host, user=settings.user)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied
```

What version of postgreSQL do i need to use?
In this case i used 10 and 9.5.

**Comment by yevheniy2407** [comment]
the problem was solved by changing
`conn = psycopg2.connect(database=settings.database, host=settings.host, user=settings.user, password=settings.password)`

**Comment by hartleybrody** [comment]
Sounds like you figured it out. The params you need to pass to connect to postgres may vary depending on what version of postgres you're using. Since this repo is meant as a sample code and doesn't have an explicit set of versioned dependencies, I don't think there's anything to change or fix around this.
